
language: node_js
node_js:
  - v10.16.0

before_script:
# - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
# - chmod +x ./cc-test-reporter
# - ./cc-test-reporter before-build
- npm install codeclimate-test-reporter istanbul -g

script:
   - npm install && npm run test
   - npm run coverage

# after_script:
# - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# after_success:
#   - npm run coverage
#   - npm run coveralls

notifications:
  email: false  
